version: '3'

services:

  ecommerce_scraper_server:

    working_dir: /usr/src/app

    build:
      context: ./server
      dockerfile: Dockerfile
    
    restart: always

    container_name: ecommerce_scraper_server

    ports:
      - "8081:8081"

    expose:
      - "8081"

    # this command will import db and run the server.
    command: "bash -c npx primsa migrate dev && npm run start" 
