version: '3'

services:

  ecommerce_server:

    working_dir: /usr/src/app

    build:
      context: ./server
      dockerfile: Dockerfile
    
    restart: always

    container_name: ecommerce_server

    ports:
      - "8081:8081"

    expose:
      - "8081"

    command: "bash -c npm run start"
