version: '3'

services:

  ecommerce_server:
    working_dir: /app
    container_name: ecommerce_server
    restart: always
    build: .
    ports:
      - 8000:8000

    expose:
      - 8000
      - 3306

    command: bash -c "npm run start"
    depends_on:
      - ecommerce_database

  ecommerce_worker:

    working_dir: /app
    container_name: ecommerce_worker
    restart: always

    ports:
      - 20010:20010

    expose:
      - 20010

    build:
      dockerfile: Dockerfile
      context: ./workers

    depends_on:
      - ecommerce_database
      - ecommerce_server

    command: bash -c "npm run start"

  ecommerce_database:

    image: mysql:5.7
    restart: always

    container_name: ecommerce_database

    expose:
      - 3306

    ports:
      - 3307:3306

    environment:
      MYSQL_DATABASE: 'ecommerce_price_tracker'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
